import {
  AVERY_ID, BRIAN_ID, JOEL_ID, JOSH_ID, MADE_ID, SAMMI_ID, SOPHIA_ID, UMA_ID,
} from './TestsContants';

export const CREATE_AVERY_USER_VARIABLES = {
  userInput: {
    _id: AVERY_ID,
    age: 21,
    birthdate: '1/11/1998',
    email: 'avery+test@getpear.com',
    emailVerified: false,
    phoneNumber: '9738738225',
    phoneNumberVerified: false,
    firstName: 'Avery',
    lastName: 'Lamp',
    gender: 'male',
    firebaseToken: 'FakeFirebaseTokenAvery',
    firebaseAuthID: 'dQEapsJzoHapRiT1fSFccrZsgSk1',
    facebookId: '2110109769065310',
    // facebookAccessToken: '2',
    thumbnailURL: 'https://platform-lookaside.fbsbx.com/platform/profilepic/?asid=2110109769065310&height=300&width=300&ext=1556961773&hash=AeQthY3WpTN3wZ5M',
    location: [-71.101366, 42.362580],
  },
};

export const CREATE_BRIAN_USER_VARIABLES = {
  userInput: {
    _id: BRIAN_ID,
    age: 20,
    birthdate: '3/15/1998',
    email: 'brian+test@getpear.com',
    emailVerified: false,
    phoneNumber: '2067789236',
    phoneNumberVerified: false,
    firstName: 'Brian',
    lastName: 'Gu',
    gender: 'male',
    firebaseToken: 'FakeFirebaseTokenBrian',
    firebaseAuthID: 'YL8kOw08SKPbKFqJMIu3Q19bQcf2',
    // facebookId: '3',
    // facebookAccessToken: '4',
    thumbnailURL: '',
    location: [-71.101366, 42.362580],
    referredByCode: 'Testcode123',
  },
};

export const CREATE_JOEL_USER_VARIABLES = {
  userInput: {
    _id: JOEL_ID,
    age: 27,
    birthdate: '1/1/1992',
    email: 'joel+test@getpear.com',
    emailVerified: false,
    phoneNumber: '7777777777',
    phoneNumberVerified: false,
    firstName: 'Joel',
    lastName: 'Aguero',
    gender: 'male',
    firebaseToken: 'FakeFirebaseTokenJoel',
    firebaseAuthID: 'yTDQITLfqKbCe4cPirAr4B54ehP2',
    // facebookId: '3',
    // facebookAccessToken: '4',
    thumbnailURL: '',
    location: [-122.422484, 37.751370],
    locationName: 'San Francisco, CA',
  },
};

export const CREATE_JOSH_USER_VARIABLES = {
  userInput: {
    _id: JOSH_ID,
    age: 20,
    birthdate: '7/14/1998',
    email: 'joshua+test@getpear.com',
    emailVerified: false,
    phoneNumber: '7897897898',
    phoneNumberVerified: false,
    firstName: 'Josh',
    lastName: 'Lee',
    gender: 'male',
    firebaseToken: 'FakeFirebaseTokenJosh',
    firebaseAuthID: 'WHtSw32a8aU8zE2hSPuKgYvWqE43',
    // facebookId: '3',
    // facebookAccessToken: '4',
    thumbnailURL: '',
    location: [-71.332174, 42.299819],
  },
};

export const CREATE_SAMMI_USER_VARIABLES = {
  userInput: {
    _id: SAMMI_ID,
    age: 19,
    birthdate: '1/1/2000',
    email: 'sammi+test@getpear.com',
    emailVerified: false,
    phoneNumber: '9788733736',
    phoneNumberVerified: false,
    firstName: 'Sammi',
    lastName: 'Cheung',
    gender: 'female',
    firebaseToken: 'FakeFirebaseTokenSammi',
    firebaseAuthID: 'HqNMSq5HpGUSk7faoQHYOqJUzxS2',
    // facebookId: '3',
    // facebookAccessToken: '4',
    thumbnailURL: '',
    location: [-71.098088, 42.355988],
  },
};

export const CREATE_MADE_USER_VARIABLES = {
  userInput: {
    _id: MADE_ID,
    age: 20,
    birthdate: '1/1/1999',
    email: 'made+test@getpear.com',
    emailVerified: false,
    phoneNumber: '6092402838',
    phoneNumberVerified: false,
    firstName: 'Made',
    lastName: 'Lapuerta',
    gender: 'female',
    firebaseToken: 'FakeFirebaseTokenMade',
    firebaseAuthID: 'MuBTB7biEpXeg5wsSfIhsQFlWw23',
    firebaseRemoteInstanceID: 'fMbqTzGeW3k:APA91bHn1m1qKrq87fGU_F9RpHbFXzcrB6X3-5iKcdUdG4her3T7nOyIxzF1SgDFqJKnL-luIZfArcelsU-9yzwhM8XRycrzMbRJhCeoQYb9h05VpuVcKCDjgseWJjkc2NHqUhDjKa9w',
    // facebookId: '3',
    // facebookAccessToken: '4',
    thumbnailURL: '',
    location: [-71.116492, 42.373999],
  },
};

export const CREATE_UMA_USER_VARIABLES = {
  userInput: {
    _id: UMA_ID,
    age: 21,
    birthdate: '1/1/1998',
    email: 'uma+test@getpear.com',
    emailVerified: false,
    phoneNumber: '9784296614',
    phoneNumberVerified: false,
    firstName: 'Uma',
    lastName: 'Roy',
    gender: 'female',
    firebaseToken: 'FakeFirebaseTokenUma',
    firebaseAuthID: 'FakeFirebaseAuthUma',
    // facebookId: '3',
    // facebookAccessToken: '4',
    thumbnailURL: '',
    location: [-71.226725, 42.444342],
  },
};

export const CREATE_SOPHIA_USER_VARIABLES = {
  userInput: {
    _id: SOPHIA_ID,
    age: 20,
    birthdate: '1/1/1999',
    email: 'sophia+test@getpear.com',
    emailVerified: false,
    phoneNumber: '9165189165',
    phoneNumberVerified: false,
    firstName: 'Sophia',
    lastName: 'Tang',
    gender: 'female',
    firebaseToken: 'FakeFirebaseTokenSophia',
    firebaseAuthID: 'PZAauXixqFZUsqf7izjbcbtdhe73',
    firebaseRemoteInstanceID: 'faBZOThoNlU:APA91bEbDB-QNxKE5aOYhvUJdwEJjsAbE1h8jih-2EgbXUEpsLbGL4e0SUO-5NATRmeXNrNKml2qirVBsc_S3bxvqGeBbIUejWAUKuffrz1QsKEDmPYZSzZzRiG4pvS-aiN7jRlndC3K',
    // facebookId: '3',
    // facebookAccessToken: '4',
    thumbnailURL: '',
    location: [-71.116492, 42.373999],
  },
};
