import {
  CREATE_AVERY_USER_VARIABLES, CREATE_BRIAN_USER_VARIABLES,
  CREATE_JOEL_USER_VARIABLES,
  CREATE_JOSH_USER_VARIABLES, CREATE_MADE_USER_VARIABLES,
  CREATE_SAMMI_USER_VARIABLES, CREATE_SOPHIA_USER_VARIABLES, CREATE_UMA_USER_VARIABLES,
} from './CreateUserVars';
import {
  CREATE_AVERY1_DETACHED_PROFILE_VARIABLES,
  CREATE_BRIAN1_DETACHED_PROFILE_VARIABLES,
  CREATE_JOSH1_DETACHED_PROFILE_VARIABLES,
  CREATE_MADE1_DETACHED_PROFILE_VARIABLES,
  CREATE_SAMMI1_DETACHED_PROFILE_VARIABLES,
  CREATE_SAMMI2_DETACHED_PROFILE_VARIABLES,
  CREATE_SOPHIA1_DETACHED_PROFILE_VARIABLES,
  CREATE_SOPHIA2_DETACHED_PROFILE_VARIABLES,
  CREATE_UMA1_DETACHED_PROFILE_VARIABLES,
} from './CreateDetachedProfileVars';
import {
  ATTACH_AVERY1_PROFILE_VARIABLES,
  ATTACH_BRIAN1_PROFILE_VARIABLES,
  ATTACH_JOSH1_PROFILE_VARIABLES,
  ATTACH_MADE1_PROFILE_VARIABLES,
  ATTACH_SAMMI1_PROFILE_VARIABLES,
  ATTACH_SAMMI2_PROFILE_VARIABLES,
  ATTACH_SOPHIA1_PROFILE_VARIABLES,
  ATTACH_SOPHIA2_PROFILE_VARIABLES,
  ATTACH_UMA1_PROFILE_VARIABLES,
} from './AttachProfileVars';
import {
  ACCEPT_REQUEST_1_VARIABLES,
  ACCEPT_REQUEST_3_1_VARIABLES,
  ACCEPT_REQUEST_3_2_VARIABLES,
  ACCEPT_REQUEST_4_1_VARIABLES,
  ACCEPT_REQUEST_4_2_VARIABLES,
  REJECT_REQUEST_5_1_VARIABLES,
  REJECT_REQUEST_5_2_VARIABLES, REJECT_REQUEST_6_1_VARIABLES,
  SEND_MATCHMAKER_REQUEST_3_VARIABLES,
  SEND_MATCHMAKER_REQUEST_4_VARIABLES,
  SEND_MATCHMAKER_REQUEST_5_VARIABLES,
  SEND_MATCHMAKER_REQUEST_6_VARIABLES,
  SEND_PERSONAL_REQUEST_1_VARIABLES,
  SEND_PERSONAL_REQUEST_2_VARIABLES, UNMATCH_1_VARIABLES, UNMATCH_2_VARIABLES,
} from './MatchActionVars';
import {
  AVERY_UPDATE_FEED,
  BRIAN_UPDATE_FEED,
  JOSH_UPDATE_FEED, MADE_UPDATE_FEED,
  SAMMI_UPDATE_FEED, SOPHIA_UPDATE_FEED, UMA_UPDATE_FEED,
} from './UpdateFeedVars';
import {
  VIEW_AVERY1_PROFILE_VARIABLES,
  VIEW_BRIAN1_PROFILE_VARIABLES,
  VIEW_JOSH1_PROFILE_VARIABLES,
  VIEW_MADE1_PROFILE_VARIABLES,
  VIEW_SAMMI1_PROFILE_VARIABLES,
  VIEW_SAMMI2_PROFILE_VARIABLES,
  VIEW_SOPHIA1_PROFILE_VARIABLES,
  VIEW_SOPHIA2_PROFILE_VARIABLES,
  VIEW_UMA1_PROFILE_VARIABLES,
} from './ViewDetachedProfileVars';
import { UPDATE_BRIAN_VARIABLES, UPDATE_JOEL_VARIABLES } from './UpdateUserVars';
import {
  EDIT_AVERY1_USER_PROFILE_VARIABLES,
  EDIT_SOPHIA1_USER_PROFILE_VARIABLES, EDIT_UMA1_USER_PROFILE_VARIABLES,
} from './EditUserProfileVars';
import {
  EDIT_BRIAN1_DETACHED_PROFILE_VARIABLES, EDIT_SOPHIA2_DETACHED_PROFILE_VARIABLES,
  EDIT_UMA1_DETACHED_PROFILE_VARIABLES,
} from './EditDetachedProfileVars';

export const createUsers = [
  CREATE_AVERY_USER_VARIABLES,
  CREATE_BRIAN_USER_VARIABLES,
  CREATE_JOEL_USER_VARIABLES,
  CREATE_JOSH_USER_VARIABLES,
  CREATE_SAMMI_USER_VARIABLES,
  CREATE_MADE_USER_VARIABLES,
  CREATE_UMA_USER_VARIABLES,
  CREATE_SOPHIA_USER_VARIABLES,
];

export const createDetachedProfiles = [
  CREATE_AVERY1_DETACHED_PROFILE_VARIABLES,
  CREATE_BRIAN1_DETACHED_PROFILE_VARIABLES,
  CREATE_JOSH1_DETACHED_PROFILE_VARIABLES,
  CREATE_SAMMI1_DETACHED_PROFILE_VARIABLES,
  CREATE_SAMMI2_DETACHED_PROFILE_VARIABLES,
  CREATE_MADE1_DETACHED_PROFILE_VARIABLES,
  CREATE_UMA1_DETACHED_PROFILE_VARIABLES,
  CREATE_SOPHIA1_DETACHED_PROFILE_VARIABLES,
  CREATE_SOPHIA2_DETACHED_PROFILE_VARIABLES,
];

export const editDetachedProfiles = [
  EDIT_UMA1_DETACHED_PROFILE_VARIABLES,
  EDIT_BRIAN1_DETACHED_PROFILE_VARIABLES,
  EDIT_SOPHIA2_DETACHED_PROFILE_VARIABLES,
];

export const viewDetachedProfiles = [
  VIEW_AVERY1_PROFILE_VARIABLES,
  VIEW_BRIAN1_PROFILE_VARIABLES,
  VIEW_JOSH1_PROFILE_VARIABLES,
  VIEW_SAMMI1_PROFILE_VARIABLES,
  VIEW_SAMMI2_PROFILE_VARIABLES,
  VIEW_MADE1_PROFILE_VARIABLES,
  VIEW_UMA1_PROFILE_VARIABLES,
  VIEW_SOPHIA1_PROFILE_VARIABLES,
  VIEW_SOPHIA2_PROFILE_VARIABLES,
];

export const attachProfiles = [
  ATTACH_AVERY1_PROFILE_VARIABLES,
  ATTACH_BRIAN1_PROFILE_VARIABLES,
  ATTACH_JOSH1_PROFILE_VARIABLES,
  ATTACH_SAMMI1_PROFILE_VARIABLES,
  ATTACH_SAMMI2_PROFILE_VARIABLES,
  ATTACH_MADE1_PROFILE_VARIABLES,
  ATTACH_UMA1_PROFILE_VARIABLES,
  ATTACH_SOPHIA1_PROFILE_VARIABLES,
  ATTACH_SOPHIA2_PROFILE_VARIABLES,
];

export const updateUsers = [
  UPDATE_BRIAN_VARIABLES,
  UPDATE_JOEL_VARIABLES,
];

export const updateFeeds = [
  AVERY_UPDATE_FEED,
  BRIAN_UPDATE_FEED,
  JOSH_UPDATE_FEED,
  SAMMI_UPDATE_FEED,
  MADE_UPDATE_FEED,
  UMA_UPDATE_FEED,
  SOPHIA_UPDATE_FEED,
];

export const sendPersonalRequests = [
  SEND_PERSONAL_REQUEST_1_VARIABLES,
  SEND_PERSONAL_REQUEST_2_VARIABLES,
];

export const sendMatchmakerRequests = [
  SEND_MATCHMAKER_REQUEST_3_VARIABLES,
  SEND_MATCHMAKER_REQUEST_4_VARIABLES,
  SEND_MATCHMAKER_REQUEST_5_VARIABLES,
  SEND_MATCHMAKER_REQUEST_6_VARIABLES,
];

export const acceptRequests = [
  ACCEPT_REQUEST_1_VARIABLES,
  ACCEPT_REQUEST_3_1_VARIABLES,
  ACCEPT_REQUEST_3_2_VARIABLES,
  ACCEPT_REQUEST_4_1_VARIABLES,
  ACCEPT_REQUEST_4_2_VARIABLES,
];

export const rejectRequests = [
  // REJECT_REQUEST_2_VARIABLES,
  // REJECT_REQUEST_4_2_VARIABLES,
  REJECT_REQUEST_5_1_VARIABLES,
  REJECT_REQUEST_5_2_VARIABLES,
  REJECT_REQUEST_6_1_VARIABLES,
];

export const unmatches = [
  UNMATCH_1_VARIABLES,
  UNMATCH_2_VARIABLES,
];

export const editUserProfiles = [
  EDIT_AVERY1_USER_PROFILE_VARIABLES,
  EDIT_SOPHIA1_USER_PROFILE_VARIABLES,
  EDIT_UMA1_USER_PROFILE_VARIABLES,
];
