import {
  CREATE_AVERY_USER_VARIABLES,
  CREATE_BRIAN_USER_VARIABLES,
  CREATE_EMPTY_USER_0,
  CREATE_EMPTY_USER_1, CREATE_EMPTY_USER_2, CREATE_EMPTY_USER_3,
  CREATE_JOEL_USER_VARIABLES,
  CREATE_JOSH_USER_VARIABLES,
  CREATE_MADE_USER_VARIABLES,
  CREATE_SAMMI_USER_VARIABLES,
  CREATE_SOPHIA_USER_VARIABLES,
  CREATE_UMA_USER_VARIABLES,
} from './CreateUserVars';
import {
  CREATE_AVERY1_DETACHED_PROFILE_VARIABLES,
  CREATE_BRIAN1_DETACHED_PROFILE_VARIABLES,
  CREATE_JOSH1_DETACHED_PROFILE_VARIABLES,
  CREATE_MADE1_DETACHED_PROFILE_VARIABLES,
  CREATE_SAMMI1_DETACHED_PROFILE_VARIABLES,
  CREATE_SAMMI2_DETACHED_PROFILE_VARIABLES,
  CREATE_SOPHIA1_DETACHED_PROFILE_VARIABLES,
  CREATE_SOPHIA2_DETACHED_PROFILE_VARIABLES,
  CREATE_UMA1_DETACHED_PROFILE_VARIABLES,
} from './CreateDetachedProfileVars';
import {
  ATTACH_AVERY1_PROFILE_VARIABLES,
  // ATTACH_BRIAN1_PROFILE_VARIABLES,
  ATTACH_JOSH1_PROFILE_VARIABLES,
  ATTACH_MADE1_PROFILE_VARIABLES,
  ATTACH_SAMMI1_PROFILE_VARIABLES,
  ATTACH_SAMMI2_PROFILE_VARIABLES,
  ATTACH_SOPHIA1_PROFILE_VARIABLES,
  ATTACH_SOPHIA2_PROFILE_VARIABLES,
  ATTACH_UMA1_PROFILE_VARIABLES,
} from './AttachProfileVars';
import {
  ACCEPT_REQUEST_1_VARIABLES,
  ACCEPT_REQUEST_3_1_VARIABLES,
  ACCEPT_REQUEST_3_2_VARIABLES,
  ACCEPT_REQUEST_4_1_VARIABLES,
  ACCEPT_REQUEST_4_2_VARIABLES,
  REJECT_REQUEST_5_1_VARIABLES,
  REJECT_REQUEST_5_2_VARIABLES, REJECT_REQUEST_6_1_VARIABLES,
  SEND_MATCHMAKER_REQUEST_3_VARIABLES,
  SEND_MATCHMAKER_REQUEST_4_VARIABLES,
  SEND_MATCHMAKER_REQUEST_5_VARIABLES,
  SEND_MATCHMAKER_REQUEST_6_VARIABLES,
  SEND_PERSONAL_REQUEST_1_VARIABLES,
  SEND_PERSONAL_REQUEST_2_VARIABLES, UNMATCH_1_VARIABLES, UNMATCH_2_VARIABLES,
} from './MatchActionVars';
import {
  AVERY_UPDATE_FEED,
  BRIAN_UPDATE_FEED,
  JOSH_UPDATE_FEED, MADE_UPDATE_FEED,
  SAMMI_UPDATE_FEED, SOPHIA_UPDATE_FEED, UMA_UPDATE_FEED,
} from './UpdateFeedVars';
import {
  VIEW_AVERY1_PROFILE_VARIABLES,
  VIEW_BRIAN1_PROFILE_VARIABLES,
  VIEW_JOSH1_PROFILE_VARIABLES,
  VIEW_MADE1_PROFILE_VARIABLES,
  VIEW_SAMMI1_PROFILE_VARIABLES,
  VIEW_SAMMI2_PROFILE_VARIABLES,
  VIEW_SOPHIA1_PROFILE_VARIABLES,
  VIEW_SOPHIA2_PROFILE_VARIABLES,
  VIEW_UMA1_PROFILE_VARIABLES,
} from './ViewDetachedProfileVars';
import {
  EDIT_SAMMI1_ENDORSEMENT_VARIABLES,
  EDIT_SAMMI2_ENDORSEMENT_VARIABLES,
} from './EditEndorsementVars';
import {
  EDIT_SAMMI1_DETACHED_PROFILE_VARIABLES,
} from './EditDetachedProfileVars';
import { ADD_QUESTIONS_VARIABLES } from './TestQuestions';
import {
  UPDATE_AVERY_FIRSTNAME_USER_VARIABLES,
  UPDATE_BRIAN_FIRSTNAME_USER_VARIABLES,
  UPDATE_JOEL_FIRSTNAME_USER_VARIABLES,
  UPDATE_JOSH_FIRSTNAME_USER_VARIABLES,
  UPDATE_MADE_FIRSTNAME_USER_VARIABLES,
  UPDATE_SAMMI_FIRSTNAME_USER_VARIABLES,
  UPDATE_SOPHIA_FIRSTNAME_USER_VARIABLES,
  UPDATE_UMA_FIRSTNAME_USER_VARIABLES,
} from './UpdateUserFirstNameVars';
import {
  UPDATE_SOPHIA_USER_VARIABLES,
  UPDATE_AVERY_USER_VARIABLES,
  UPDATE_BRIAN_USER_VARIABLES,
  UPDATE_JOEL_USER_VARIABLES,
  UPDATE_JOSH_USER_VARIABLES,
  UPDATE_SAMMI_USER_VARIABLES,
  UPDATE_MADE_USER_VARIABLES,
  UPDATE_UMA_USER_VARIABLES,
} from './UpdateUserVars';
import {
  ADD_TO_BRIAN_QUEUE0,
  ADD_TO_BRIAN_QUEUE1,
  ADD_TO_BRIAN_QUEUE2,
  ADD_TO_BRIAN_QUEUE3,
} from './AddToQueue';
import {
  ADD_BRIAN_EVENT0,
  ADD_MADE_EVENT0,
  CREATE_EVENT0_VARIABLES,
  CREATE_EVENT1_VARIABLES,
} from './EventVars';

export const addQuestions = ADD_QUESTIONS_VARIABLES;

export const createEvents = [
  CREATE_EVENT0_VARIABLES,
  CREATE_EVENT1_VARIABLES,
];

export const createUsers = [
  CREATE_AVERY_USER_VARIABLES,
  CREATE_BRIAN_USER_VARIABLES,
  CREATE_JOEL_USER_VARIABLES,
  CREATE_JOSH_USER_VARIABLES,
  CREATE_SAMMI_USER_VARIABLES,
  CREATE_MADE_USER_VARIABLES,
  CREATE_UMA_USER_VARIABLES,
  CREATE_SOPHIA_USER_VARIABLES,
];

export const createDetachedProfiles = [
  CREATE_AVERY1_DETACHED_PROFILE_VARIABLES,
  CREATE_BRIAN1_DETACHED_PROFILE_VARIABLES,
  CREATE_JOSH1_DETACHED_PROFILE_VARIABLES,
  CREATE_SAMMI1_DETACHED_PROFILE_VARIABLES,
  CREATE_SAMMI2_DETACHED_PROFILE_VARIABLES,
  CREATE_MADE1_DETACHED_PROFILE_VARIABLES,
  CREATE_UMA1_DETACHED_PROFILE_VARIABLES,
  CREATE_SOPHIA1_DETACHED_PROFILE_VARIABLES,
  CREATE_SOPHIA2_DETACHED_PROFILE_VARIABLES,
];

export const updateUserFirstNames = [
  UPDATE_AVERY_FIRSTNAME_USER_VARIABLES,
  UPDATE_BRIAN_FIRSTNAME_USER_VARIABLES,
  UPDATE_JOEL_FIRSTNAME_USER_VARIABLES,
  UPDATE_JOSH_FIRSTNAME_USER_VARIABLES,
  UPDATE_SAMMI_FIRSTNAME_USER_VARIABLES,
  UPDATE_MADE_FIRSTNAME_USER_VARIABLES,
  UPDATE_UMA_FIRSTNAME_USER_VARIABLES,
  UPDATE_SOPHIA_FIRSTNAME_USER_VARIABLES,
];

export const addEventCodes = [
  ADD_BRIAN_EVENT0,
  ADD_MADE_EVENT0,
];

export const editDetachedProfiles = [
  EDIT_SAMMI1_DETACHED_PROFILE_VARIABLES,
];

export const viewDetachedProfiles = [
  VIEW_AVERY1_PROFILE_VARIABLES,
  VIEW_BRIAN1_PROFILE_VARIABLES,
  VIEW_JOSH1_PROFILE_VARIABLES,
  VIEW_SAMMI1_PROFILE_VARIABLES,
  VIEW_SAMMI2_PROFILE_VARIABLES,
  VIEW_MADE1_PROFILE_VARIABLES,
  VIEW_UMA1_PROFILE_VARIABLES,
  VIEW_SOPHIA1_PROFILE_VARIABLES,
  VIEW_SOPHIA2_PROFILE_VARIABLES,
];

export const attachProfiles = [
  ATTACH_AVERY1_PROFILE_VARIABLES,
  // ATTACH_BRIAN1_PROFILE_VARIABLES,
  ATTACH_JOSH1_PROFILE_VARIABLES,
  ATTACH_SAMMI1_PROFILE_VARIABLES,
  ATTACH_SAMMI2_PROFILE_VARIABLES,
  ATTACH_MADE1_PROFILE_VARIABLES,
  ATTACH_UMA1_PROFILE_VARIABLES,
  ATTACH_SOPHIA1_PROFILE_VARIABLES,
  ATTACH_SOPHIA2_PROFILE_VARIABLES,
];

export const updateUsers = [
  UPDATE_AVERY_USER_VARIABLES,
  UPDATE_BRIAN_USER_VARIABLES,
  UPDATE_JOEL_USER_VARIABLES,
  UPDATE_JOSH_USER_VARIABLES,
  UPDATE_SAMMI_USER_VARIABLES,
  UPDATE_MADE_USER_VARIABLES,
  UPDATE_UMA_USER_VARIABLES,
  UPDATE_SOPHIA_USER_VARIABLES,
];

export const updateFeeds = [
  AVERY_UPDATE_FEED,
  BRIAN_UPDATE_FEED,
  JOSH_UPDATE_FEED,
  SAMMI_UPDATE_FEED,
  MADE_UPDATE_FEED,
  UMA_UPDATE_FEED,
  SOPHIA_UPDATE_FEED,
];

export const sendPersonalRequests = [
  SEND_PERSONAL_REQUEST_1_VARIABLES,
  SEND_PERSONAL_REQUEST_2_VARIABLES,
];

export const sendMatchmakerRequests = [
  SEND_MATCHMAKER_REQUEST_3_VARIABLES,
  SEND_MATCHMAKER_REQUEST_4_VARIABLES,
  SEND_MATCHMAKER_REQUEST_5_VARIABLES,
  SEND_MATCHMAKER_REQUEST_6_VARIABLES,
];

export const acceptRequests = [
  ACCEPT_REQUEST_1_VARIABLES,
  ACCEPT_REQUEST_3_1_VARIABLES,
  ACCEPT_REQUEST_3_2_VARIABLES,
  ACCEPT_REQUEST_4_1_VARIABLES,
  ACCEPT_REQUEST_4_2_VARIABLES,
];

export const rejectRequests = [
  // REJECT_REQUEST_2_VARIABLES,
  // REJECT_REQUEST_4_2_VARIABLES,
  REJECT_REQUEST_5_1_VARIABLES,
  REJECT_REQUEST_5_2_VARIABLES,
  REJECT_REQUEST_6_1_VARIABLES,
];

export const unmatches = [
  UNMATCH_1_VARIABLES,
  UNMATCH_2_VARIABLES,
];

export const editEndorsements = [
  EDIT_SAMMI1_ENDORSEMENT_VARIABLES,
  EDIT_SAMMI2_ENDORSEMENT_VARIABLES,
];

export const createEmptyUsers = [
  CREATE_EMPTY_USER_0,
  CREATE_EMPTY_USER_1,
  CREATE_EMPTY_USER_2,
  CREATE_EMPTY_USER_3,
];

export const addToBrianQueue = [
  ADD_TO_BRIAN_QUEUE0,
  ADD_TO_BRIAN_QUEUE1,
  ADD_TO_BRIAN_QUEUE2,
  ADD_TO_BRIAN_QUEUE3,
];
