#!/bin/bash

echo "Starting testing scripts"
sleep 2

REGENDB=true yarn startdev &

sleep 10

RESULT=$(curl http://localhost:1234/test-client)
echo $RESULT

if [ $RESULT == "success" ]; then
  echo "All Tests Passed"
  exit 0
else
  echo "Tests Failed"
  exit 1
fi
